//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AluraTunes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist
    {
        public Playlist()
        {
            this.Faixas = new HashSet<Faixa>();
        }
    
        public int PlaylistId { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Faixa> Faixas { get; set; }
    }
}
